// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CaveRunnersResources
{
        public const string leaderboard_level_1 = "CgkIi7HoiqAfEAIQBw"; // <GPGSID>
        public const string leaderboard_level_2 = "CgkIi7HoiqAfEAIQCA"; // <GPGSID>
        public const string achievement_joining_cave_runners = "CgkIi7HoiqAfEAIQAQ"; // <GPGSID>
        public const string achievement_shatter_crystals = "CgkIi7HoiqAfEAIQAg"; // <GPGSID>
        public const string leaderboard_level_5 = "CgkIi7HoiqAfEAIQCw"; // <GPGSID>
        public const string leaderboard_level_6 = "CgkIi7HoiqAfEAIQDA"; // <GPGSID>
        public const string leaderboard_level_7 = "CgkIi7HoiqAfEAIQDQ"; // <GPGSID>
        public const string leaderboard_level_3 = "CgkIi7HoiqAfEAIQCQ"; // <GPGSID>
        public const string leaderboard_level_4 = "CgkIi7HoiqAfEAIQCg"; // <GPGSID>
        public const string achievement_ressurection = "CgkIi7HoiqAfEAIQAw"; // <GPGSID>
        public const string achievement_gem_collector = "CgkIi7HoiqAfEAIQBA"; // <GPGSID>
        public const string achievement_finished_tutorial = "CgkIi7HoiqAfEAIQBQ"; // <GPGSID>
        public const string leaderboard_weekly_leaderboards = "CgkIi7HoiqAfEAIQBg"; // <GPGSID>

}

